# Generated by Django 2.0.3 on 2018-04-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180330_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='value',
            new_name='name',
        ),
    ]
